[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient

[env:esp8266-queue-fs-test]
extends = env:esp8266
build_flags = -DECOWITT_QUEUE_FS_TEST=1
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m1m.ld